### ISSUE TITLE
Taking $returnvalue into account before processing notifications

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/html_email_handler#18]
The attended behaviour would be that if a plugin hooked into object:notifications, and returned "true", this should break the notification process.
The $returnvalue is not taken into account yet in function html_email_handler_object_notifications_hook($hook, $entity_type, $returnvalue, $params), so notifications are sent whatever previous hooks returned.

I suggest adding following line into lib/hooks to let html_email_handler be aware of previous plugins returns :

if ($returnvalue === true) return true;

I'll wait for the file attachment PR before submitting that one.

**Comment by jeabakker** [comment]
this was fixed in https://github.com/ColdTrick/html_email_handler/commit/2ed485b810d4a3c493b4b290a68539661ed974d7#diff-7fdf8b450742eb07530da59d54ec680fR43
