### ISSUE TITLE
recipient is not being passed in to message body

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/html_email_handler#32]
i noticed that the footer of the emails was not being populated with the text and link in 1.11.2.
i identified that the cause of this is that the body.php file looks for the recipient object in the vars array and it is no longer present.
i resolved this by adding the following code to the top of body.php:

```
$notification = elgg_extract("notification", $vars);
if ($notification)
    $recipient = $notification->getRecipient();
else
    $recipient = elgg_extract("recipient", $vars);
```

**Comment by jdalsem** [comment]
Was already fixed in master: https://github.com/ColdTrick/html_email_handler/commit/9b249185cea0c9814a6b7eac1749ba6a0164b28a

**Comment by propertunist** [comment]
oh ok, though that commit is not the right change/fix is it?

**Comment by jdalsem** [comment]
you are correct...
