### ISSUE TITLE
html_email 3.0 & 3.1

### ISSUE THREAD

**Issue by merilturock** [ColdTrick/html_email_handler#35]
In 3.0 version user validation is not been received for the end user (as for this some Bad parameters is passed in the validation mail so it does not delivers the validation email. I have no idea how to get that bad parameter)

in 3.1 when activated for elgg 1.12 white screen error is received

**Comment by jdalsem** [comment]
Why do you think these problems are related to this plugin?

**Comment by merilturock** [comment]
In elgg 1.12 when i activate 3.1 version html_email_handler my website goes to a white screen..

For 3.0 version user is not getting the validation mail but when i disable the plugin user is able to get the validation mail.

**Comment by jdalsem** [comment]
Is there anything in the PHP error log?

**Comment by jdalsem** [comment]
Did you have a look at the error log? Let me know if there is any extra information as i can not reproduce the issues. I will reopen this issue if you have more information
