### ISSUE TITLE
Plain text version and user settings

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/html_email_handler#36]
I recently had users asking if they could choose to receive email notifications in plain text version instead of HTML, and gave a new look at this plugin with alternate versions in mind, which raised a few thoughts :

The current plugin behaviour with plain text / HTML is: 
- "plain text" version is sent only if it was explicitely defined in html_email_handler_send_email options
- "HTML version is sent only if it was explicitely defined in html_email_handler_send_email options
- if neither plain text nor HTML version is defined, html_email_handler_send_email defines will sent both versions based on 'body' option.

This raises a few concerns :
- most plugins are not html_email_handler aware and will use only 'body' var, so most of the times messages will be sent using both HTML and plaintext versions, BUT the plain text version is not always HTML (HTML tags are not stripped off in the process)
- when HTML emails are sent, there is not always an alternate text-only version along
- there is no option for a user to decide whether he wants to receive HTML or TEXT or both versions.

I would suggest the following additions / changes to the plugin :
1. add a usersetting option, so users can set if they prefer to receive HTML or text only versions, or both ("both" would bethe default choice, to keep the current behaviour). Optionally the availability of this option itself could be controlled by an admin-setting, but i do not think it's worth it.
2. automatically add a text-only version to email (except if HTML only is set as a user choice).
3. systematically strip HTML tags from text-only version.

If you think this could be added to html_email_handler i can make the work and submit a PR - which would be for Elgg 1.12 version.
What do you think ?

**Comment by Facyla** [comment]
Hi !
Any feedback on this ?   I'm OK to make the changes and submit a PR but it would be better to agree on which changes before :)

Thinking again about it, i think point 3) would be the main change, and a very quick and easy fix so users who have the email client configured with text-only would receive a clean text email (they would actually receive both but without any risk of having HTML in text-inly version).

The usersetting option seems more like a gadget, except if we want to handle cases where there is a very limited bandwith and every bytes count, then setting text-only email and sending only that version would save some bandwith.

Regards

**Comment by jdalsem** [comment]
Hi @Facyla,

the changes you propose make sense, however we are actually trying to get rid of the html_email_handler plugin by moving all its features into Elgg v3. Maybe there will still be a need for the html_email_handler plugin in the future, but i am a bit hesitant regarding pulling in new features at this moment, because i do not know what will be left over...

On the other hand, if you submit a PR, we could also try to get those changes into core... Unfortunately that will not be for Elgg 1.12.

New features for html_email_handler should not be added to the 1.12 version anyway (unless you are willing to port them to the Elgg 2.x version of this plugin also...)

**Comment by Facyla** [comment]
Hi Jeroen,

That definitely would be a great move to have this integrated into core, nice for the future :)

However my current concern is about production sites in 1.12 that use this plugin and people complaining about not being able to receive text-only versions - and also that further versions do not lack the new functionnality. I've already made a quick fix that overrides the email,system hook to replace function \ColdTrick\HTMLEmailHandler\Email::emailHandler, but that's not very sustainable, and some plugins that use the html_email_handler_send_email() function directly can not benefit for the change with this workaround so it would be better to make a change in the plugin itself.

Porting the changes to master branch should not be a big deal once done in elgg_19 branch, and these are very small changes anyway, so i can submit a PR for both versions.
Probably the simpler the better, plus the more i think about having a usersetting the more i think it's a bad idea after all (setting is usually on email client side anyway, not on sending application).
So i'll stick with the 2 most basic changes :
 - always ensure there is an alternate text version
 - and always ensure it is actually plain-text and not HTML

PRs coming soon ;)

**Comment by Facyla** [comment]
PRs submitted !

**Comment by jdalsem** [comment]
This has been fixed in the Elgg 4 core email features
