### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [ColdTrick/html_email_handler#42]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0. This also provides compatibility with PHP 7.2.

**Comment by jeabakker** [comment]
thanks for the update, will check it out

**Comment by jeabakker** [comment]
fixed in 128f345aec7c04b1eff0df646addf35990c6f34d
