### ISSUE TITLE
Group Mail Test

### ISSUE THREAD

**Issue by umbergerba** [ColdTrick/html_email_handler#9]
Tested the group mail option and received the following in my inbox ...

##########

--my site name 527627d26de1c
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

PHA+VGVzdGluZyAxMjM8L3A+CgpGcm9tIGdyb3VwOiBIZWxwIENlbnRlciBbaHR0cDovL2RlYWQt
Z2FtZXJzLXNvY2lldHkuY29tL2dyb3Vwcy9wcm9maWxlLzEzOS9oZWxwLWNlbnRlcl0=

--my site name 527627d26de1c
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64

PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgVHJhbnNpdGlvbmFs
Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXRyYW5zaXRpb25h
bC5kdGQiPgo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCIgeG1sOmxh
bmc9ImVuIiBsYW5nPSJlbiI+CjxoZWFkPgo8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LVR5cGUi
IGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD1VVEYtOCI+CjxiYXNlIHRhcmdldD0iX2JsYW5r
Ij4KPHRpdGxlPlRlc3QgR3JvdXAgTWFpbCAyPC90aXRsZT4KPC9oZWFkPgo8Ym9keSBzdHlsZT0n
Zm9udDogMTJweC8xN3B4ICJMdWNpZGEgR3JhbmRlIiwgVmVyZGFuYSwgc2Fucy1zZXJpZjsNCgkJ
CQljb2xvcjogIzMzMzMzMzsnPg0KCQk8c3R5bGUgdHlwZT0idGV4dC9jc3MiPg0KCQkJYm9keSB7
DQoJCQkJZm9udDogMTJweC8xN3B4ICJMdWNpZGEgR3JhbmRlIiwgVmVyZGFuYSwgc2Fucy1zZXJp
ZjsNCgkJCQljb2xvcjogIzMzMzMzMzsNCgkJCX0NCgkJCQ0KCQkJYSB7DQoJCQkJY29sb3I6ICM0
NjkwZDY7DQoJCQl9DQoJCQkNCgkJCSNub3RpZmljYXRpb25fY29udGFpbmVyIHsNCgkJCQlwYWRk
aW5nOiAyMHB4IDA7DQoJCQkJd2lkdGg6IDYwMHB4Ow0KCQkJCW1hcmdpbjogMCBhdXRvOw0KCQkJ
fQ0KCQkNCgkJCSNub3RpZmljYXRpb25faGVhZGVyIHsNCgkJCQl0ZXh0LWFsaWduOiByaWdodDsN
CgkJCQlwYWRkaW5nOiAwIDAgMTBweDsNCgkJCX0NCgkJCQ0KCQkJI25vdGlmaWNhdGlvbl9oZWFk
ZXIgYSB7DQoJCQkJdGV4dC1kZWNvcmF0aW9uOiBub25lOw0KCQkJCWZvbnQtd2VpZ2h0OiBib2xk
Ow0KCQkJCWNvbG9yOiAjMDA1NEE3Ow0KCQkJCWZvbnQtc2l6ZTogMThweDsNCgkJCX0NCgkJDQoJ
CQkjbm90aWZpY2F0aW9uX3dyYXBwZXIgew0KCQkJCWJhY2tncm91bmQ6ICNERURFREU7DQoJCQkJ
cGFkZGluZzogMTBweDsNCgkJCX0NCgkJCQ0KCQkJI25vdGlmaWNhdGlvbl93cmFwcGVyIGgyIHsN
CgkJCQltYXJnaW46IDVweCAwIDVweCAxMHB4Ow0KCQkJCWNvbG9yOiAjMDA1NEE3Ow0KCQkJCWZv
bnQtc2l6ZTogMTZweDsNCgkJCQlsaW5lLWhlaWdodDogMjBweDsNCgkJCX0NCgkJCQ0KCQkJI25v
dGlmaWNhdGlvbl9jb250ZW50IHsNCgkJCQliYWNrZ3JvdW5kOiAjRkZGRkZGOw0KCQkJCXBhZGRp
bmc6IDEwcHg7DQoJCQl9DQoJCQkNCgkJCSNub3RpZmljYXRpb25fZm9vdGVyIHsNCgkJCQkNCgkJ
CQltYXJnaW46IDEwcHggMCAwOw0KCQkJCWJhY2tncm91bmQ6ICNCNkI2QjY7DQoJCQkJcGFkZGlu
ZzogMTBweDsNCgkJCQl0ZXh0LWFsaWduOiByaWdodDsNCgkJCX0NCgkJCQ0KCQkJI25vdGlmaWNh
dGlvbl9mb290ZXJfbG9nbyB7DQoJCQkJZmxvYXQ6IGxlZnQ7DQoJCQl9DQoJCQkNCgkJCSNub3Rp
ZmljYXRpb25fZm9vdGVyX2xvZ28gaW1nIHsNCgkJCQlib3JkZXI6IG5vbmU7DQoJCQl9DQoJCQkN
CgkJCS5jbGVhcmZsb2F0IHsNCgkJCQljbGVhcjpib3RoOw0KCQkJCWhlaWdodDowOw0KCQkJCWZv
bnQtc2l6ZTogMXB4Ow0KCQkJCWxpbmUtaGVpZ2h0OiAwcHg7DQoJCQl9DQoJCQkNCgkJPC9zdHls
ZT4KPGRpdiBpZD0ibm90aWZpY2F0aW9uX2NvbnRhaW5lciIgc3R5bGU9InBhZGRpbmc6IDIwcHgg
MDsNCgkJCQl3aWR0aDogNjAwcHg7DQoJCQkJbWFyZ2luOiAwIGF1dG87Ij4NCgkJCTxkaXYgaWQ9
Im5vdGlmaWNhdGlvbl9oZWFkZXIiIHN0eWxlPSJ0ZXh0LWFsaWduOiByaWdodDsNCgkJCQlwYWRk
aW5nOiAwIDAgMTBweDsiPg0KCQkJCTxhIGhyZWY9Imh0dHA6Ly9kZWFkLWdhbWVycy1zb2NpZXR5
LmNvbS8iIHN0eWxlPSJjb2xvcjojMDA1NEE3O3RleHQtZGVjb3JhdGlvbjpub25lO2ZvbnQtd2Vp
Z2h0OmJvbGQ7Zm9udC1zaXplOjE4cHg7Ij5UaGUgRGVhZCBHYW1lcnMgU29jaWV0eeKEojwvYT4J
CQk8L2Rpdj4NCgkJCTxkaXYgaWQ9Im5vdGlmaWNhdGlvbl93cmFwcGVyIiBzdHlsZT0iYmFja2dy
b3VuZDogI0RFREVERTsNCgkJCQlwYWRkaW5nOiAxMHB4OyI+DQoJCQkJPGgyIHN0eWxlPSJtYXJn
aW46IDVweCAwIDVweCAxMHB4Ow0KCQkJCWNvbG9yOiAjMDA1NEE3Ow0KCQkJCWZvbnQtc2l6ZTog
MTZweDsNCgkJCQlsaW5lLWhlaWdodDogMjBweDsiPlRlc3QgR3JvdXAgTWFpbCAyPC9oMj4JCQkN
CgkJCQk8ZGl2IGlkPSJub3RpZmljYXRpb25fY29udGVudCIgc3R5bGU9ImJhY2tncm91bmQ6ICNG
RkZGRkY7DQoJCQkJcGFkZGluZzogMTBweDsiPg0KCQkJCQk8cD5UZXN0aW5nIDEyMzwvcD4KPGJy
Pjxicj4KRnJvbSBncm91cDogSGVscCBDZW50ZXIgWzxhIGhyZWY9Imh0dHA6Ly9kZWFkLWdhbWVy
cy1zb2NpZXR5LmNvbS9ncm91cHMvcHJvZmlsZS8xMzkvaGVscC1jZW50ZXIlNUQiIHJlbD0ibm9m
b2xsb3ciIHN0eWxlPSJjb2xvcjogIzQ2OTBkNjsiPmh0dHA6Ly9kZWFkLWdhbWVycy1zb2NpZXR5
LmNvbS9ncm91cHMvcHJvZmlsZS8xMzkvaGVscC1jZW50ZXJdPC9hPgkJCQk8L2Rpdj4NCgkJCTwv
ZGl2Pg0KCQkJDQoJCQk8ZGl2IGlkPSJub3RpZmljYXRpb25fZm9vdGVyIiBzdHlsZT0ibWFyZ2lu
OiAxMHB4IDAgMDsNCgkJCQliYWNrZ3JvdW5kOiAjQjZCNkI2Ow0KCQkJCXBhZGRpbmc6IDEwcHg7
DQoJCQkJdGV4dC1hbGlnbjogcmlnaHQ7Ij4NCgkJCQk8YSBocmVmPSJodHRwOi8vd3d3LmVsZ2cu
b3JnLyIgaWQ9Im5vdGlmaWNhdGlvbl9mb290ZXJfbG9nbyIgc3R5bGU9ImNvbG9yOiM0NjkwZDY7
ZmxvYXQ6bGVmdDsiPg0KCQkJCQk8aW1nIHNyYz0iaHR0cDovL2RlYWQtZ2FtZXJzLXNvY2lldHku
Y29tL19ncmFwaGljcy9wb3dlcmVkX2J5X2VsZ2dfYmFkZ2VfZHJrX2Jja2duZC5naWYiIHN0eWxl
PSJib3JkZXI6IG5vbmU7Ij48L2E+DQoJCQkJDQoJCQkJQ29uZmlndXJlIHlvdXIgbm90aWZpY2F0
aW9uIHNldHRpbmdzIDxhIGhyZWY9Imh0dHA6Ly9kZWFkLWdhbWVycy1zb2NpZXR5LmNvbS9ub3Rp
ZmljYXRpb25zL3BlcnNvbmFsIiBzdHlsZT0iY29sb3I6ICM0NjkwZDY7Ij5oZXJlPC9hPgkJCQk8
ZGl2IGNsYXNzPSJjbGVhcmZsb2F0IiBzdHlsZT0iY2xlYXI6Ym90aDsNCgkJCQloZWlnaHQ6MDsN
CgkJCQlmb250LXNpemU6IDFweDsNCgkJCQlsaW5lLWhlaWdodDogMHB4OyI+PC9kaXY+DQoJCQk8
L2Rpdj4NCgkJPC9kaXY+DQoJPC9ib2R5Pgo8L2h0bWw+Cg==

--my site name 527627d26de1c--

--Boundary_(ID_vdvvESFftW22OBGYw179rw)--

##########

Suggestions?

Umby

**Comment by jdalsem** [comment]
closing due to lack of information
